Adds a contributors page and README (with maps :) )
UX-Wizards/design-system-web pull request #17
Opened 2021-03-11 06:17 UTC by dm36

2021-03-11 07:42 UTC, kaisenl commented on UXWContributors.js
> +      {data.map(({name, role, email, img}) => {
`{data.map(({name, role, email, image}) => (`

2021-03-11 07:43 UTC, kaisenl commented on UXWContributors.js
> +            <img src={img} alt="Jane" style={{width: '100%'}} />
`image`

2021-03-11 07:43 UTC, kaisenl commented on UXWContributors.js
> +        </div>})}
`</div>))}`

2021-03-14 00:55 UTC, javag97 requested changes

2021-03-14 00:55 UTC, javag97 commented on README.md
> +php -S localhost:9000
**Praise**: Docs!

2021-03-14 00:55 UTC, javag97 commented on UXWContributors.js
> +      <h1>Meet The Ux Wizards!</h1>
**Small Suggestion**: Change Ux → UX

2021-03-14 00:55 UTC, javag97 commented on UXWContributors.js
> +          <div className="card" style={cardStyle}>
**Suggestion**(non-blocking): I would consider making the whole card clickable if you're looking to add a contact button to it.

2021-03-14 00:55 UTC, javag97 commented on UXWContributors.js
> +const buttonStyle = {
I Will always encourage you to use tailwindCSS 😄 , but this is ok to me.

2021-03-14 00:55 UTC, javag97 commented on UXWContributors.js
> +  "font-size": "10px"
**Suggestion**(non-blocking): Text is rather small IMO. I would default to [body text being one root em](https://www.w3.org/Style/Examples/007/units.en.html). Browsers default this value to be `16px`, so I would start here and make adjustments from this baseline

2021-03-18 04:36 UTC, javag97 approved these changes
Approval! We can collaborate on TailwindCSS in another PR :-)

2021-03-18 18:59 UTC, merged